channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2020.12.5
  - certifi=2020.12.5
  - cmake=3.14.0
  - curl=7.71.1
  - expat=2.2.9
  - krb5=1.17.1
  - libcurl=7.71.1
  - libcxx=10.0.0
  - libedit=3.1.20191231
  - libffi=3.3
  - libssh2=1.9.0
  - libuv=1.41.0
  - make=4.2.1
  - ncurses=6.2
  - openssl=1.1.1k
  - pip=21.0.1
  - python=3.8.8
  - python_abi=3.8
  - readline=8.1
  - rhash=1.4.1
  - setuptools=52.0.0
  - sqlite=3.35.2
  - tk=8.6.10
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
